version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.2

jobs:
  build-and-push-image:
    docker:
      - image: cimg/python:3.12 
    parameters:
      aws-access-key-id:
        default: AWS_ACCESS_KEY_ID
        type: env_var_name
      aws-secret-access-key:
        default: AWS_SECRET_ACCESS_KEY
        type: env_var_name
      region:
        default: AWS_DEFAULT_REGION
        type: env_var_name
      account-url:
        default: AWS_ECR_ACCOUNT_URL
        type: env_var_name
      repo:
        description: Name of the Amazon ECR repository
        type: string
      env:
        description: Environment name (dev/staging/prod)
        type: string
      path:
        default: .
        description: Path to the directory containing your Dockerfile
        type: string
      dockerfile:
        default: Dockerfile
        description: Dockerfile name
        type: string
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: <<parameters.aws-access-key-id>>
          aws-region: <<parameters.region>>
          aws-secret-access-key: <<parameters.aws-secret-access-key>>
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image to ECR
          command: |
            # Automatically set tag with current timestamp for uniqueness
            TAG=$(date +%Y%m%d%H%M%S)-<<parameters.env>>
            echo "🔹 Building Docker image with tag: $TAG"

            # Login to ECR
            aws ecr get-login-password --region $<<parameters.region>> \
              | docker login --username AWS --password-stdin $<<parameters.account-url>>

            # Build the Docker image
            docker build -f <<parameters.dockerfile>> -t <<parameters.repo>> <<parameters.path>>

            # Tag and push the image
            docker tag <<parameters.repo>>:latest $<<parameters.account-url>>/<<parameters.repo>>:$TAG
            docker push $<<parameters.account-url>>/<<parameters.repo>>:$TAG

            echo "✅ Successfully pushed: $<<parameters.account-url>>/<<parameters.repo>>:$TAG"

workflows:
  version: 2
  build-and-push:
    jobs:
      - build-and-push-image:
          name: build-and-push-dev
          repo: urbanstitch-ecs
          env: dev
          context: urbanstitch-context
          filters:
            branches:
              only: dev

      - build-and-push-image:
          name: build-and-push-staging
          repo: urbanstitch-ecs
          env: staging
          context: urbanstitch-context
          filters:
            branches:
              only: staging

      - build-and-push-image:
          name: build-and-push-prod
          repo: urbanstitch-ecs
          env: prod
          context: urbanstitch-context
          filters:
            branches:
              only:
                - main
                - prod
              